version: '2.1'
services:
  terraform:
    image: quay.io/azavea/terraform:0.10.8
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=$AWS_PROFILE
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    working_dir: /usr/local/src
    entrypoint: bash
  packer:
    image: hashicorp/packer:1.3.1
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=$AWS_PROFILE
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    working_dir: /usr/local/src
    entrypoint: bash
